FROM jboss/keycloak-ha-postgres

# COPY /themes /opt/jboss/keycloak/themes/
# COPY /deployments /opt/jboss/keycloak/standalone/deployments/
COPY ./standalone-ha.xml /opt/jboss/keycloak/standalone/configuration/